log_dir: ./log/04
model_saved_dir: ./output/04
# feeder
feeder: pre_data.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_joint.npy
  label_path: ./data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/test_joint.npy
  label_path: ./data/test_label.npy

# model
model: model.dmodel.Model
model_path: './output/04/weights.pt'
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: pre_data.graph.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
optimizer: 'SGD'
weight_decay: 1e-4
base_lr: 0.1
step: [30,40]

# training
device: 0
batch_size: 128
num_epoch: 50
nesterov: True

# testing
test_path: '/home/user50102/.conda/envs/sxc/Skelton/output/04/weights.pt'
test_batch_size: 32
test_device: 1
